#server:
#  servlet:
#    contextPath: /api
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/baemin
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 500
    open-in-view: false
logging:
  level:
    org.hibernate.type: trace
    org.hibernate.SQL: debug
