springdoc:
  packages-to-scan: com.example.baemin
  paths-to-match: /**
  swagger-ui:
    path: /swagger-ui
    display-request-duration: true
server:
  port: 8080
  servlet:
    contextPath: /api
spring:
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/baemin
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 500
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
logging:
  level:
    org.hibernate.type: trace
    org.hibernate.SQL: debug
